# Specify version format
version: "{build}"

# Operating system (build VM template)
os: Visual Studio 2017

# build platform, i.e. Win32 (instead of x86), x64, Any CPU. This setting is optional.
platform:
  - Win32

configuration:
  - Release

# clone directory
clone_folder: C:\projects\png2tile

# scripts to run before build
before_build:
  - cmd: cd C:\projects\png2tile
  - cmd: md build
  - cmd: cd build
  - cmd: cmake -G "Visual Studio 15 2017" ..

after_build:
  - cmd: 7z a c:\projects\png2tile\png2tile.zip c:\projects\png2tile\build\Release\png2tile.exe c:\projects\png2tile\LICENSE c:\projects\png2tile\README.md

artifacts:
  - path: png2tile.zip
    name: png2tile
